name: rsapidatabulk

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  getAndSaveData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        API_DATA_FILE: ./rsdata.js
        API_DATA_ALCH_FILE: ./rsdataalch.js
        API_DATA_WATCH_FILE: ./rsdatawatch.js
        API_ITEM_DIRECTORY: ./items/
        API_SEARCH_FILE: ./rsapidatawikisearch.js
        API_UPDATED_FILE: ./rsapiupdated.json
        ITEMS_DATA_FILE: ./rsitems.sh
        ALCH_DATA_FILE: ./rsitemsalch.sh
        WATCH_DATA_FILE: ./rsitemswatch.json
        IMAGE_OUTPUT_DIR: ./images
      run: |
        bash ./.github/scripts/rsapidatawikibulk.sh
        if [[ `git status --porcelain` ]]; then
        git config --global user.name 'RS3 Data Bot'
        git config --global user.email '20735294+607ch00@users.noreply.github.com'
        git add -A
        git commit -m "[RS3 Data Bot] API Data fetch"
        git push
        fi
