name: rsapidata

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  getAndSaveData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        API_UPDATED_FILE: ./rsapiupdated.json
        API_DATA_FILE: ./rsapidatawiki.js
        ITEMS_DATA_FILE: ./rsitems.json
      run: |
        bash ./.github/scripts/rsapidatawiki.sh
        if [[ `git status --porcelain` ]]; then
        git config --global user.name 'RS3 Data Bot'
        git config --global user.email '20735294+607ch00@users.noreply.github.com'
        git commit -am "[RS3 Data Bot] API Data fetch"
        git push
        fi
