name: rselydata

on:
  schedule:
    - cron: "42 */4 * * *"
  workflow_dispatch:

jobs:
  getAndSaveData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        ELY_UPDATED_FILE: ./rselyupdated.json
        ELY_DATA_FILE: ./rselydata.js
        ELY_ITEMS_FILE: ./rselyitems.json
        ELY_MAP_FILE: ./rsitemswatch.json
      run: |
        bash ./.github/scripts/rselydata.sh
        if [[ `git status --porcelain` ]]; then
        git config --global user.name 'RS3 Data Bot'
        git config --global user.email '20735294+607ch00@users.noreply.github.com'
        git commit -am "[RS3 Data Bot] Ely Data fetch"
        git push
        fi
